export const authText = {
  credentialsError: "Failed to login. Please check your credentials.",
  enterEmailPassword: "Enter your email and password to login to your account",
  welcomeBack: "Welcome back",
  emailOrUsernamePlaceholder: "convo@example.com or johndoe",
  emailOrUsername: "Email or Username",
  usernamePlaceholder: "johndoe",
  firstNamePlaceholder: "John",
  lastNamePlaceholder: "Doe",
  password: "Password",
  emailPlaceholder: "convo@example.com",
  confirmPassword: "Confirm Password",
  register: "Register",
  login: "Login",
  loggingIn: "Logging in...",
  dontHaveAccount: "Don't have an account? ",
  registrationFailed: "Registration failed. Please try again.",
  enterDetails: "Enter your details below to create your account",
  firstName: "First name",
  lastName: "Last name",
  email: "Email",
  username: "Username",
  creatingAccount: "Creating account...",
  createAccount: "Create account",
  alreadyHaveAccount: "Already have an account? ",
};

export const inviteText = {
  invitedYou: "invited you to chat on Convo",
  acceptInvite: "Accept Invite",
  continueToConversation: "Continue to Conversation",
  signInToContinue: "Sign in to continue",
  loading: "Loading invite...",
  joining: "Joining...",
  invalidTitle: "Invite not found",
  invalidDescription:
    "This invite link is invalid or has expired. Please ask for a new one.",
  alreadyAcceptedTitle: "Already accepted",
  alreadyAcceptedDescription: "You've already joined this conversation.",
  openChat: "Open chat",
  welcomeBackInvitee: "Welcome back",
  welcomeBackDescription: "You were invited by",
  joinedToast: "joined the conversation",
  pendingTitle: "Pending Invitation",
  youInvited: "You invited",
  waitingToJoin: "Waiting for them to join",
  waitingFor: "Waiting for",
  reminderSent: "Reminder sent successfully!",
  rateLimitDefault: "You can only send one invite every 24 hours.",
  rateLimitFallback: "Rate limit exceeded.",
  resendFailed: "Failed to resend invite.",
  sentBadge: "Sent!",
  resendInvite: "Resend Invite",
  resendIn: "Resend in",
  invitationSent: "Invitation sent!",
  sendingInvite: "Sending invite...",
  inviteSentBadge: "Invite Sent",
  sendInvite: "Send Invite",
  availableIn: "Available in",
  noUserFound: "No user found",
  startConversationWith: "Start conversation with",
  tryDifferentSearch: "Try a different username or email",
  typeAtLeastNChars: "Type at least 2 characters to search",
  startConversationFailed: "Couldn't start a conversation. Please try again.",
  sendInviteFailed: "Couldn't send invite. Please try again.",
};

export const landingText = {
  tagline: "A secured messaging app",
  login: "Login",
  register: "Register",
};

export const dashboardText = {
  chatDashboard: "Chat Dashboard",
  messagesHeading: "Messages",
  startConversationTitle: "Start a conversation",
  startConversationDescription:
    "Search for someone by their username or email to send them a message.",
  notesToSelfTitle: "Notes to self",
  sayHi: "Say hi 👋",
  notesToSelfDescription: "Save thoughts, links, and reminders just for you.",
  conversationStartWith: "This is the start of your conversation",
  beginningOfConversation: "Beginning of conversation",
  selectConversationTitle: "Select a conversation",
  selectConversationHint: "Choose from the list on the left to start messaging",
  noMessagesYet: "No messages yet",
  messageDeleted: "Message deleted",
  meSuffix: "(Me)",
  pendingBadge: "Pending",
  youPrefix: "You",
  justNow: "just now",
};

export const sharedText = {
  requiredSymbol: "*",
  logout: "Logout",
  logoutAriaLabel: "Log out",
  signOut: "Sign out",
  themeToggle: "Toggle theme",
  themeToggleAriaLabel: "Theme Toggle",
  switchToDark: "Switch to dark mode",
  switchToLight: "Switch to light mode",
  userMenuAriaLabel: "Account menu",
  viewProfile: "View profile",
  backToChat: "Back to chat",
  backToConversations: "Back to conversations",
  profileHeading: "Profile",
  profilePicture: "Profile picture",
  changePicture: "Change picture",
  changePictureAriaLabel: "Change profile picture",
  removePicture: "Remove picture",
  memberSince: "Member since",
  notSet: "Not set",
  editProfile: "Edit profile",
  editProfileComingSoon: "Editing your details is coming soon.",
  comingSoon: "Coming soon",
  cancel: "Cancel",
  save: "Save",
  tryAgain: "Try again",
  searching: "Searching…",
  conversationFallback: "Conversation",
  youFallback: "You",
  // Message composer
  messageInputLabel: "Message",
  messageInputPlaceholder: "Type a message…",
  sendMessageAriaLabel: "Send message",
  // Search
  searchPlaceholder: "Search by username or email…",
  clearSearchAriaLabel: "Clear search",
  // Sidebar
  newConversationAriaLabel: "New conversation",
  newConversationTitle: "New conversation",
  newConversationDialogLabel: "Start a new conversation",
  editAvatarAriaLabel: "Edit avatar",
  zoomAvatarAriaLabel: "Zoom avatar",
  avatarZoomDialogLabel: "Profile picture preview",
  // Message bubble
  editMessageAriaLabel: "Edit message",
  deleteMessageAriaLabel: "Delete message",
  deleteMessagePrompt: "Delete this message?",
  sendingAriaLabel: "Sending",
  failedToSendAriaLabel: "Failed to send",
  seenAriaLabel: "Seen",
  deliveredAriaLabel: "Delivered",
  sentAriaLabel: "Sent",
  editedSuffix: "(edited)",
  unreadAriaLabel: "Unread",
};

export const presenceText = {
  online: "Online",
  away: "Away",
  offline: "Offline",
  setStatus: "Set Status",
};

export const errorText = {
  loadConversationsFailed: "Failed to load conversations. Please try again.",
  loadMessagesFailed: "Failed to load messages. Please try again.",
  uploadAvatarFailed: "Failed to upload avatar.",
};

export const connectionText = {
  disconnected: "Disconnected — reload to retry",
  reconnecting: "Reconnecting…",
  connecting: "Connecting…",
};
