# Generated by Django 6.0.4 on 2026-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_conversation_conversation_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="prev_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
