# Generated by Django 6.0.4 on 2026-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_message_deleted_at_message_prev_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
